### ISSUE TITLE
Guide and information on using legate

### ISSUE THREAD

**Issue by Sh4zKh4n** [nv-legate/legate.core#1]
Legate got suggested as a library I should look at during a couple of sessions I attended at GTC2021. I just wondered if there was somewhere or someone I could get some information on how to use the library? My use case is with volume data, which is array data. From the slides from GTC 2020, it appears that the data is split a bit like a quad tree implementation. It would be greatto get some information how to use.

**Comment by marcinz** [comment]
We currently have two libraries of interest released publically:

- Pandas: https://github.com/nv-legate/legate.pandas
- Numpy: https://github.com/nv-legate/legate.numpy

It sounds like you may be more interested in Numpy for your application. If you already use Numpy, than you should be able to just run your program using Legate Numpy. For a quick start, you can find some examples on how to use the Docker images we provide here:

https://github.com/nv-legate/quickstart#using-a-pre-built-docker-image

If you have a program that already uses Numpy, simply replace `import numpy as np` with `import legate.numpy as np`. After you do this, simply run your program through legate as shown in the link above. 

Let us know if you have any further issues. Instead of discussing it here, the better place may be our mailing list at legate@nvidia.com.
