### ISSUE TITLE
The driver does not accept the -c option to run Python commands

### ISSUE THREAD

**Issue by marcinz** [nv-legate/legate.core#568]
This used to work:

```
legate --verbose -c 'import legate.core'
```

However, now the driver rejects the `-c` option. Furthermore, even `python -c "import legate.core"` does not work because the `-c` option causes an unrecognized command error. I think that both cases should work.

**Comment by bryevdv** [comment]
I believe this was broken when we switched to using `nargs.REMAINDER` and strict `parse_args` instead of `parse_known_args` in the driver preparation. As a reminder this was done in order not to have to assume that the user script ends in `.py` or that it is any particular (e.g.) first such arg. 

The reason there is a problem is that, absolutely inexplicably to me, python does not remove *its own* `-c` arg from `sys.argv` when you run a snippet with `-c`:
```
base ❯ python -c "import sys; print(sys.argv)" 

['-c']
```
to be honest I think I would consider this a bug in Python, though I would maybe guess that the rationale is that `-c` is  for running tiny code snippets, not anything of any significance, and certainly not anything doing *argument parsing*, so it can't possibly matter what is in `sys.argv` for `python -c` invocations. 

cc @manopapad

**Comment by magnatelee** [comment]
@marcinz though this looks like a legitimate issue to fix, can't we do the check with `python` now?

**Comment by bryevdv** [comment]
@magnatelee you would think (I did!) but no, it is worse
```
dev310 ❯ python -c "import legate.core"         
usage: -c [-h] [--nodes NODES] [--ranks-per-node RANKS_PER_NODE] [--no-replicate] [--launcher {mpirun,jsrun,srun,none}] [--launcher-extra LAUNCHER_EXTRA] [--cpu-bind CPU_BIND] [--mem-bind MEM_BIND] [--gpu-bind GPU_BIND]
          [--nic-bind NIC_BIND] [--cpus CPUS] [--gpus GPUS] [--omps OPENMP] [--ompthreads OMPTHREADS] [--utility UTILITY] [--sysmem SYSMEM] [--numamem NUMAMEM] [--fbmem FBMEM] [--zcmem ZCMEM] [--regmem REGMEM]
          [--eager-alloc-percentage EAGER_ALLOC] [--profile] [--cprofile] [--nvprof] [--nsys] [--nsys-targets NSYS_TARGETS] [--nsys-extra NSYS_EXTRA] [--logging USER_LOGGING_LEVELS] [--logdir LOGDIR] [--log-to-file] [--keep-logs]
          [--gdb] [--cuda-gdb] [--memcheck] [--freeze-on-error] [--gasnet-trace] [--dataflow] [--event] [--progress] [--mem-usage] [--verbose] [--bind-detail] [--module MODULE] [--dry-run] [--rlwrap] [--color]
          ...
-c: error: unrecognized arguments: -c
```

**Comment by bryevdv** [comment]
I do think the change above is the appropriate change, in fact.

**Comment by bryevdv** [comment]
Also in the `legate` driver case this worked in the past only due to happy circumstance. The `-c "stuff"` was part of "extra" so it just got punted on to `legion_python` to handle. 

To support this for the driver we will need to explicitly add our own `-c` arg for argparsing (which may also be tricky due to the ways that argparse sucks for single-dash options... but it may be ok)
